/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#32353c',
        'inverse-primary': '#005ac2',
        'secondary-container': '#39485a',
        'on-tertiary-fixed-variant': '#723600',
        'error': '#ffb4ab',
        'on-tertiary-container': '#461f00',
        'on-tertiary': '#502400',
        'inverse-on-surface': '#2e3038',
        'on-primary': '#002e6a',
        'surface-bright': '#363941',
        'tertiary-fixed': '#ffdcc6',
        'tertiary': '#ffb786',
        'on-surface': '#e1e2ec',
        'outline-variant': '#424754',
        'on-primary-fixed': '#001a42',
        'primary-fixed': '#d8e2ff',
        'on-primary-container': '#00285d',
        'tertiary-fixed-dim': '#ffb786',
        'error-container': '#93000a',
        'on-background': '#e1e2ec',
        'on-tertiary-fixed': '#311400',
        'surface-container-low': '#191b23',
        'primary-fixed-dim': '#adc6ff',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#39485a',
        'primary-container': '#4d8eff',
        'secondary': '#b9c8de',
        'primary': '#adc6ff',
        'surface-container-highest': '#32353c',
        'surface': '#10131a',
        'background': '#10131a',
        'on-surface-variant': '#c2c6d6',
        'on-primary-fixed-variant': '#004395',
        'on-error': '#690005',
        'secondary-fixed-dim': '#b9c8de',
        'surface-container': '#1d2027',
        'surface-dim': '#10131a',
        'tertiary-container': '#df7412',
        'surface-tint': '#adc6ff',
        'surface-container-high': '#272a31',
        'surface-container-lowest': '#0b0e15',
        'on-secondary-fixed': '#0d1c2d',
        'on-secondary-container': '#a7b6cc',
        'outline': '#8c909f',
        'on-secondary': '#233143',
        'inverse-surface': '#e1e2ec',
        'secondary-fixed': '#d4e4fa',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xl: '64px',
        'margin-mobile': '16px',
        md: '24px',
        lg: '40px',
        base: '4px',
        gutter: '24px',
        'margin-desktop': '48px',
        sm: '16px',
        xs: '8px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-lg': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'headline-xl': ['Inter'],
        'label-sm': ['JetBrains Mono'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
